services:
  db:
    image: postgres:18-alpine
    container_name: blogsphere-db
    restart: always
    environment:
      POSTGRES_DB: blogspheredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "hunter@9797"
    ports:
      - "5001:5432"
    volumes:
      - blogsphere_pg_data:/var/lib/postgresql/data
    networks:
      - blogsphere-ntw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blogspheredb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  blogsphere-api:
    container_name: blogsphere-api
    image: shubham/blogsphere:1.0.0
    ports:
      - "8080:8080"
    networks:
      - blogsphere-ntw
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  blogsphere-ntw:
    driver: bridge

volumes:
  blogsphere_pg_data:
    name: blogsphere_pg_data