services:
  db:
    image: postgres:16-alpine
    container_name: blogsphere-db
    restart: always
    environment:
      POSTGRES_DB: blogspheredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "hunter@9797"
    ports:
      - "5001:5432"
    volumes:
      - blogsphere_pg_data:/var/lib/postgresql/data
    networks:
      - blogsphere-ntw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  blogsphere-api:
    container_name: blogsphere-api
    image: ${DOCKER_USERNAME:-shubham}/blogsphere-api:${API_VERSION:-latest}
    ports:
      - "8080:8080"
    networks:
      - blogsphere-ntw
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    
  blogsphere-ui:
    container_name: blogsphere-ui
    image: ${DOCKER_USERNAME:-shubham}/blogsphere-ui:${UI_VERSION:-latest}
    ports:
      - "80:80"
    networks:
      - blogsphere-ntw
    depends_on:
      blogsphere-api:
        condition: service_started

networks:
  blogsphere-ntw:
    driver: bridge

volumes:
  blogsphere_pg_data:
    name: blogsphere_pg_data