services:
  db:
    image: postgres:18-alpine
    container_name: blogsphere
    restart: always
    environment:
      POSTGRES_DB: blogspheredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "hunter@9797"
    ports:
      - "5001:5432"
    volumes:
      - blogsphere_data:/var/lib/postgresql/data

volumes:
  blogsphere_data: